from music21.key import Key


Cb_MAJOR = Key("C-")
Gb_MAJOR = Key("G-")
Db_MAJOR = Key("D-")
Ab_MAJOR = Key("A-")
Eb_MAJOR = Key("E-")
Bb_MAJOR = Key("B-")
F_MAJOR = Key("F")
C_MAJOR = Key("C")
G_MAJOR = Key("G")
D_MAJOR = Key("D")
A_MAJOR = Key("A")
E_MAJOR = Key("E")
B_MAJOR = Key("B")
Fs_MAJOR = Key("F#")
Cs_MAJOR = Key("C#")

Ab_MINOR = Key("a-")
Eb_MINOR = Key("e-")
Bb_MINOR = Key("b-")
F_MINOR = Key("f")
C_MINOR = Key("c")
G_MINOR = Key("g")
D_MINOR = Key("d")
A_MINOR = Key("a")
E_MINOR = Key("e")
B_MINOR = Key("b")
Fs_MINOR = Key("f#")
Cs_MINOR = Key("c#")
Gs_MINOR = Key("g#")
Ds_MINOR = Key("d#")
As_MINOR = Key("a#")
